// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added2NewPropertiesToApplicationUser_Modif : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added2NewPropertiesToApplicationUser_Modif));
        
        string IMigrationMetadata.Id
        {
            get { return "201807031054045_Added2NewPropertiesToApplicationUser_Modif"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
